### ISSUE TITLE
Yet another prior art

### ISSUE THREAD

**Issue by tugrul** [tc39/proposal-iterator-helpers#108]
I recently discovered a library can give different aspect.

http://fitzgen.github.io/wu.js/

**Comment by kriszyp** [comment]
I don't know if you are looking for more prior art, but https://github.com/DoctorEvidence/lmdb-store/blob/master/util/ArrayLikeIterable.js#L13 is just another example of using array-like methods, with lazy execution, on iterators. In this case it is used for iterating through a database query with a cursor, which is a classic use case for iterators and their lazy helpers since you can iterate through tables that may be much larger than available memory, perform transforms along the way, and exit/return/throw at any point as well. These type of helpers definitely have valuable real-world application, and having in the language would be nice.

**Comment by michaelficarra** [comment]
Thank you for the references. For this first milestone, we have a very small budget. Some of these could serve as inspiration for great follow-on proposals.
