### ISSUE TITLE
Merge with Standard Library proposal?

### ISSUE THREAD

**Issue by friendlyanon** [tc39/proposal-iterator-helpers#20]
This proposal doesn't introduce any new mechanic that needs changes to be made to the core language that otherwise we can't really already do, so I think adding one more thing to the global namespace is unnecessary. Our stdlib is also in stage 1 already.

```js
import { Iterator } from "std:Iterator";
// all the rest of the fun things
```

**Comment by devsnek** [comment]
if stdlib moves forward before this does I'm open to it, but I find that to be very unlikely.

**Comment by domenic** [comment]
I don't think this issue makes a lot of sense.

First, as stated in https://github.com/tc39/proposal-javascript-standard-library/#scope, the actual contents of the standard library are not part of proposal-javascript-standard-library. So there would be no merging of proposals, since this proposes new APIs, and that proposal is only about mechanisms.

Second, this proposal is primarily about extending the existing built-in prototypes. It does add one new global namespace, but that's not the most important part of the proposal. So most of the proposal work will not be related to the code in the OP.
