### ISSUE TITLE
Compare with adding individual methods to every collection

### ISSUE THREAD

**Issue by domenic** [tc39/proposal-iterator-helpers#5]
A natural question to ask is, when should we add things to `Iterator.prototype` vs. to each of `Array.prototype`, `Set.prototype`, `Map.prototype`, etc.?

The answer is that we should do both. Each serve different use cases:

- On-collection methods allow optimized-for-each-collection implementations, that are more convenient to use in the common case. For example, a `set.map(x => y)` would return a `Set`. This is simpler than indirecting through `new Set(set.values().map(x => y))`, and semantically it is always eager, which is sometimes what you want.
- Iterator.prototype methods provide a nice way to manipulate the `.values()`, `.entries()`, and `.keys()` of an individual collection. They're always lazy, which is sometimes what you want.

Maybe link to the Set methods proposal to show how they coexist nicely.

That's my brain dump, but I'm sure it can be expanded.

**Comment by Kovensky** [comment]
This might be overengineering, but this is how I'd do it:

- All collection methods belong to the top level `Iterator.prototype`. For the most part they all can be described as manipulating the result of calling `.next()`, so in theory you should be able to take any object with a nullary `next` method and convert it into an `Iterator`.
  - I know that ES generators have a unary `next`, but they're already `instanceof Iterator`. I'm not sure how to specify their behavior here since none of the collection libraries I have as reference support passing values back into the generator coroutine. This might be a javascript-specific problem to think about.
  - `AsyncIterator` would also require their own primitives because they have to accept, unwrap, and re-wrap `Promise`s.
- Each collection that wants to have a form specialized for their use case (say, that does something more efficient than just call `.next()` a bunch of times) could subclass `Iterator`. For example, a `SetIterator`.
- Each collection could then have a bound version of the equivalent iterator method in their prototype. They could even be generated through a factory function:

```js
function iteratorEagerBind(returner, methodName) {
  const method = {
    [methodName](...args) {
      return returner(this[Symbol.iterator]()[methodName](...args))
    }
  }[methodName]
  Object.defineProperty(method, 'length', {
    value: Iterator.prototype[methodName].length
  })
  return method
}
```

```
Set.prototype.map = iteratorEagerBind(values => new Set(values), 'map')
```

**Comment by devsnek** [comment]
this conversation happened in #8
